### ISSUE TITLE
Rewrite the beats plugin in pure java

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-beats#92]
There is an ongoing effort to address #45, we took the decision to rewrite the server/protocol parser in pure java using the netty library. The WIP Feature branch is located at https://github.com/logstash-plugins/logstash-input-beats/tree/feature/java-implementation and require the `java-lumber` library located at https://github.com/elastic/java-lumber. 

The code in theses repositories are not ready for production but initial test show a big improvement in speed vs the initial ruby implementation.

### TODO
- [x] Rename `java-lumber` to  `java-lumberjack`
- [x] Remove debug mode from the library
- [x] Remove the fatJar and declare dependency with jar-dependency
- [x] Move the library into the plugin repository
- [x] Allow client auth to support multiple CAs.
- [x] Revert patch for MapJavaProxy requires https://github.com/elastic/logstash/issues/5465
- [x] Add test with Private keys in the PKCS8 format.
- [x] Fix the integration test hang, the server shutdown sucessfully but something else is blocking the main thread.
- [x] Add tests with Encrypted private keys.
- [x] Stress tests with multiples clients
- [x] MessageListener specs
- [x] make all tests pass
- [x] release beta1 plugin
- [x] clean `logger.debug` statements.

WIP PR at https://github.com/logstash-plugins/logstash-input-beats/pull/93

**Comment by ph** [comment]
Lets make sure we address too https://github.com/elastic/ruby-lumberjack/issues/10#issuecomment-228803692 I believe the sslhandler has a default settings for that but lets verify it.

**Comment by renkin** [comment]
What is the current status of this beats plugin? It is listed as Potential Candidate of 2.4 Release, but was not included as I understand.

We want to use the beats Java implementation on AIX. Currently we use the Java implementation of the deprecated Logstash-Forwarder (https://github.com/didfet/logstash-forwarder-java).

**Comment by ph** [comment]
@renkin This rewrite is only concerning a beats input for Logstash and not a new standalone client, we have beats for that need, beats itself is written in golang, but sadly there is still no support for the AIX platform see https://github.com/golang/go/issues/7208. 

I believe you only have two option:

1. This input plugin is still backward compatible with logstash-forwarder client, so you can still you the java client to connect to the beats input.

2. Run Logstash on AIX itself, though I haven't tried but it might work, but we don't officially support that platform.
